### ISSUE TITLE
Use layout management

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/WheresMyMouse#2]
Should use layout management to enable localization etc.

**Comment by owenca** [comment]
Is issue #5 related to this? How to use layout to enable localization?

**Comment by humdingerb** [comment]
An app needs to use layoutmanagement first, otherwise text in menus etc. might be truncated in other languages. Once that's done, it can be localized, see
https://www.haiku-os.org/community/getting-involved/translating/3rdparty

**Comment by owenca** [comment]
Pulkomandy has just committed my layout code. I will work on localization next.

**Comment by owenca** [comment]
Done. Please remove ~/config/settings/WhereIsMyMouse_settings before running the new version for the first time. (Or should I rename the settings file to WheresMyMouse_settings so that it would match the top folder name? But the executable is named WhereIsMyMouse, not WheresMyMouse.)

**Comment by humdingerb** [comment]
Yeah, let's keep the file name "WhereIsMyMouse"; easier to read.
So, let's see it in a PR. :)
