### ISSUE TITLE
Add setting of colour

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/WheresMyMouse#3]
The user should be able to select a colour for the circles. Just have the darkest circle colour set, the rest are computed from the number of circles.

**Comment by ahwayakchih** [comment]
IIRC there already is support for drag & drop of colors: https://github.com/HaikuArchives/WheresMyMouse/blob/0029a558c60c311112da5b2ed0279243f0b40865/source/main.cpp#L472

**UPDATE:** Just drag and drop color from http://www.yellowbites.com/wonderbrush.html or any other application that can "export" RGBColor object.

**Edit:** fixed URL, so it points to version of file with existing line.

**Comment by owenca** [comment]
Support for drag & drop of colors is moved to here:
https://github.com/HaikuArchives/WheresMyMouse/blob/master/source/DemoView.cpp#L75

**Comment by humdingerb** [comment]
I'd say d&d of colours is good enough for this small tool. Thanks!
